# Generated by Django 3.2.4 on 2021-07-06 01:25

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='アウトプットタイトル')),
                ('about', models.TextField(unique=True, verbose_name='概要')),
                ('description', models.TextField(unique=True, verbose_name='説明')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='outpro_images/', verbose_name='画像')),
                ('language', models.CharField(choices=[('Python', 'Python'), ('PHP', 'PHP'), ('JavaScript', 'JavaScript'), ('Go', 'Go'), ('Ruby', 'Ruby'), ('Java', 'Java'), ('HTML5', 'HTML5'), ('CSS3', 'CSS3')], max_length=50, verbose_name='言語')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'アウトプット',
                'verbose_name_plural': 'アウトプット',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='プログラム名')),
                ('description', models.TextField(unique=True, verbose_name='説明')),
                ('code', mdeditor.fields.MDTextField(unique=True, verbose_name='コード')),
                ('image01', models.ImageField(blank=True, upload_to='outpro_images/', verbose_name='画像')),
                ('image02', models.ImageField(blank=True, upload_to='outpro_images/', verbose_name='画像')),
                ('image03', models.ImageField(blank=True, upload_to='outpro_images/', verbose_name='画像')),
                ('image04', models.ImageField(blank=True, upload_to='outpro_images/', verbose_name='画像')),
                ('good_count', models.IntegerField(default=0, verbose_name='いいね')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('review', models.BooleanField(default=False, verbose_name='レビュー')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output.output', verbose_name='アウトプット')),
            ],
            options={
                'verbose_name': 'プログラム',
                'verbose_name_plural': 'プログラム',
            },
        ),
        migrations.CreateModel(
            name='ReviewCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('review_code', mdeditor.fields.MDTextField()),
                ('check', models.BooleanField(blank=True, default=False, verbose_name='チェック済み')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output.program', verbose_name='プログラムID')),
            ],
            options={
                'verbose_name': 'コードレビュー',
                'verbose_name_plural': 'コードレビュー',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('check', models.BooleanField(blank=True, default=False, verbose_name='メッセージチェック済み')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output.reviewcode', verbose_name='レビューモデル')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output.program', verbose_name='作品')),
            ],
            options={
                'verbose_name': 'グッド',
                'verbose_name_plural': 'グッド',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('output_id', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='output.output', verbose_name='アウトプットID')),
                ('program_id', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='output.program', verbose_name='プログラムID')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
            },
        ),
    ]
