# Generated by Django 3.2.4 on 2021-07-02 07:51

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_id', models.IntegerField(default=0, verbose_name='アウトプットID')),
            ],
            options={
                'verbose_name': 'グッド',
                'verbose_name_plural': 'グッド',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='アウトプットタイトル')),
                ('about', models.TextField(unique=True, verbose_name='概要')),
                ('description', models.TextField(unique=True, verbose_name='説明')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='outpro_images/', verbose_name='画像')),
                ('language', models.CharField(choices=[('Python', 'Python'), ('PHP', 'PHP'), ('JavaScript', 'JavaScript'), ('Go', 'Gp'), ('Ruby', 'Ruby'), ('Java', 'Java'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Ruby', 'Ruby')], max_length=50, verbose_name='言語')),
            ],
            options={
                'verbose_name': 'アウトプット',
                'verbose_name_plural': 'アウトプット',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='プログラム名')),
                ('description', models.TextField(unique=True, verbose_name='説明')),
                ('code', mdeditor.fields.MDTextField(unique=True, verbose_name='コード')),
                ('image01', models.ImageField(blank=True, upload_to='outpro_images/', verbose_name='画像')),
                ('image02', models.ImageField(blank=True, upload_to='outpro_images/', verbose_name='画像')),
                ('image03', models.ImageField(blank=True, upload_to='outpro_images/', verbose_name='画像')),
                ('image04', models.ImageField(blank=True, upload_to='outpro_images/', verbose_name='画像')),
                ('good_count', models.IntegerField(default=0, verbose_name='いいね')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output.output', verbose_name='アウトプット')),
            ],
            options={
                'verbose_name': 'プログラム',
                'verbose_name_plural': 'プログラム',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output.program', verbose_name='作品')),
            ],
            options={
                'verbose_name': 'グッド',
                'verbose_name_plural': 'グッド',
            },
        ),
    ]
