# Generated by Django 3.2.4 on 2021-06-28 01:01

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='アウトプットタイトル')),
                ('about', models.TextField(unique=True, verbose_name='概要')),
                ('description', models.TextField(unique=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'アウトプット',
                'verbose_name_plural': 'アウトプット',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='プログラム名')),
                ('description', models.TextField(unique=True, verbose_name='説明')),
                ('code', mdeditor.fields.MDTextField(verbose_name='コード')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output.output', verbose_name='アウトプット')),
            ],
            options={
                'verbose_name': 'プログラム',
                'verbose_name_plural': 'プログラム',
            },
        ),
    ]
