# Generated by Django 3.2.4 on 2021-07-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('PHP', 'PHP'), ('JavaScript', 'JavaScript'), ('Go', 'Go'), ('Ruby', 'Ruby'), ('Java', 'Java'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Ruby', 'Ruby')], max_length=50, verbose_name='言語'),
        ),
    ]
