# Generated by Django 3.2.4 on 2021-07-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0002_alter_output_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='outpro_images/', verbose_name='画像'),
        ),
    ]
