# Generated by Django 3.2.4 on 2021-07-03 03:19

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0003_alter_output_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=markdownx.models.MarkdownxField(unique=True, verbose_name='コード'),
        ),
    ]
