# Generated by Django 3.2.4 on 2021-07-03 03:26

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0004_alter_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=mdeditor.fields.MDTextField(unique=True, verbose_name='コード'),
        ),
    ]
