# Generated by Django 3.2.4 on 2021-07-03 09:49

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0005_alter_program_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('comment', models.TextField(verbose_name='コメント')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
            },
        ),
        migrations.CreateModel(
            name='ReviewCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('review_code', mdeditor.fields.MDTextField()),
            ],
            options={
                'verbose_name': 'コードレビュー',
                'verbose_name_plural': 'コードレビュー',
            },
        ),
        migrations.DeleteModel(
            name='DeleteRequest',
        ),
        migrations.AddField(
            model_name='output',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='program',
            name='review',
            field=models.BooleanField(default=False, verbose_name='レビュー'),
        ),
        migrations.AddField(
            model_name='reviewcode',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output.program', verbose_name='プログラムID'),
        ),
        migrations.AddField(
            model_name='comment',
            name='output_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='output.output', verbose_name='アウトプットID'),
        ),
        migrations.AddField(
            model_name='comment',
            name='program_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='output.program', verbose_name='プログラムID'),
        ),
    ]
