# Generated by Django 3.2.4 on 2021-07-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0006_auto_20210703_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcode',
            name='check',
            field=models.BooleanField(blank=True, default=False, verbose_name='チェック済み'),
        ),
    ]
