# Generated by Django 3.2.4 on 2021-07-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0007_reviewcode_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('check', models.BooleanField(blank=True, default=False, verbose_name='メッセージチェック済み')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output.reviewcode', verbose_name='レビューモデル')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ',
            },
        ),
    ]
