# Generated by Django 3.2.4 on 2021-07-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0009_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='output_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='output.output', verbose_name='アウトプットID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='program_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='output.program', verbose_name='プログラムID'),
        ),
    ]
